spring.application.name=AddressBookApp
 spring.datasource.url=jdbc:postgresql://localhost:5433/addressbook
 spring.datasource.username=postgres
 spring.datasource.password=0000

 spring.jpa.hibernate.ddl-auto=update